### ISSUE TITLE
Axes: Parametric (Latin Plus) Italic

### ISSUE THREAD

**Issue by sberlow** [TypeNetwork/Amstelvar#46] opened 2018-02-21 19:57 UTC
- [ ] XTRA
- [x] YTRA
- [x] XOPQ
- [ ] YOPQ

- [ ] YTLC
- [ ] YTUC

- [ ] YTAS
- [ ] YTDE

- [ ] YTFG
- [ ] YTOS
- [ ] YTUS
- [ ] YTAD
- [ ] YTDD
- [ ] XTAB
- [ ] YTSE

- [ ] VOTF

- [ ] POPS
- [ ] PWTH
- [ ] PWHT

- [ ] UDLN

**Comment by dberlow** [comment] 2018-02-28 15:19
There are not YTOS, YTUS, VUID, YTCH, XTCH or POPS axes planned for this variable font.

**Comment by dberlow** [comment] 2018-02-28 15:20
There is no XTAB axis planned for this font.

**Comment by davelab6** [comment] 2018-02-28 20:22
I thought XTAB was used for the OpenType 'tnum' feature figures?

**Comment by dberlow** [comment] 2018-02-28 20:35
X tab was Intended to vary the width of the instances of a tabular or monospaced style.

**Comment by davelab6** [comment] 2018-02-28 20:36
And tabular numbers are not a tabular style? :)

**Comment by dberlow** [comment] 2018-02-28 21:06
I count tnum as a feature to be stored either as a separate glyph, or as an instance along the votf axis.

**Comment by davelab6** [comment] 2020-10-06 16:57
Closing as related to Amstelvar Alpha

**Closed by davelab6** 2020-10-06 16:57 UTC
