### ISSUE TITLE
Posting zip of fonts.

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#77] opened 2018-05-11 11:18 UTC
Amstelvar-Roman has changed 
  ellipsis and 
  ascii circumflex

Amstelvar-Roman-YOPQ-min is all new, but accents. 

Amstelvar-Roman-XOPQ-min has minimal changes to keep up with Roman and YOPQ.

Let me know. 

thanks. 
[Amstlevar DB>DJR 5:11:18.zip](https://github.com/TypeNetwork/Amstelvar/files/1995098/Amstlevar.DB.DJR.5.11.18.zip)

**Comment by djrrb** [comment] 2018-05-12 11:57
@dberlow Received. Before I commit...was it intentional to convert these to UFO3?

**Comment by dberlow** [comment] 2018-05-12 12:04
My whole world is now ufo3, yes. I backed up my Amstelvar folder beforehand, and then went on as you see.

I am taking the weekend off, to rest from drawing, and because the process I’ve been using, and some of the extensions I work with, are broken.

I will test the vfont you make if you do make one, and then starting Monday from the git, all ufo3?

Let me know, thanks.

**Comment by djrrb** [comment] 2018-05-12 12:49
Files committed. So far attempts update the build script to accommodate UFO3 have been unsuccessful, but I’ll let you know when I have a new VF to play with (might not be this weekend though).

**Closed** 2018-05-12 12:49 UTC

**Comment by djrrb** [comment] 2018-05-12 21:46
@petrvanblokland I don’t think it attached. This build script contains modifications that copies glyphs and stuff pre-build. The issue is with converting the robofab bits to font parts, especially `font.insertGlyph()`. Any idea why this might be?

**Comment by djrrb** [comment] 2018-05-13 03:01
@dberlow Looks like Petr was able to generate a VF using the updated build script. https://github.com/TypeNetwork/Amstelvar/blob/master/fonts/Amstelvar-Roman-VF.ttf

A few additional notes:
* The rest of the UFOs were updated to UFO3. Please use these UFOs for future changes if possible.
* I had to add a notch to the second interior counter of the `f_f_l` to get it to interpolate with your new sources. In future versions you can feel free to make these match however you would like.
* I had to change the order of the semicolon contours to match the default

I will try to make sure everything is upgraded to see why I can’t build on my end. Thanks @petrvanblokland!

**Comment by dberlow** [comment] 2018-05-13 19:54
Sounds great, thanks guys!

**Comment by dberlow** [comment] 2018-05-14 11:40
YOPQ-min is in the sources, but there is no YOPQ in the variable font.

Please check build script.

**Comment by djrrb** [comment] 2018-05-14 17:02
@dberlow my bad, sorry. I’ve committed the necessary updates to the designspace and build script, as well as a new font with YOPQ axis. https://github.com/TypeNetwork/Amstelvar/blob/master/fonts/Amstelvar-Roman-VF.ttf

Got the build script working on my end, and added a [new axis checklist](https://github.com/TypeNetwork/Amstelvar/blob/master/docs/new-axis-checklist.md) so I hopefully don’t forget to do that again.

**Comment by dberlow** [comment] 2018-05-14 20:13
I am now working in this repo so you have to stop thanks
